// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxaclcxvjvmnhkwkjsic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14YWNsY3h2anZtbmhrd2tqc2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjQ4NjMsImV4cCI6MjA1OTEwMDg2M30.b7hEPRFy1-b3C6QC5u5KyPgYjVm4sCalsrPhRCoBZSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);